name: flutter_sports_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

# State & DI
  flutter_riverpod: ^2.5.1

# Routing
  go_router: ^14.2.7

# Code gen models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

# Networking (keep for future real API)
  dio: ^5.7.0

# UI helpers
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12 
  freezed: ^2.5.7 
  json_serializable: ^6.9.5 
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/mock/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

